input_files_data: ["/data3/fmazzasc/hyp_run_3/pbpb/pass4/AO2D.root"]
input_files_mc_h3l: ["/data3/fmazzasc/hyp_run_3/mc/LHC24i5/AO2D_h3l.root"]
input_files_mc_h4l: ["/data3/fmazzasc/hyp_run_3/mc/LHC24i5/AO2D_h4l.root"]

output_dir: "../results/comb_fits/"
output_file: "comb_fit_h4l_pbpb.root"
selection:
  {
    "fNSigmaHe4": "abs(fNSigmaHe4) < 2",
    "fPt": "fPt > 2.",
    "fCosPA": "fCosPA > 0.99999",
    "fNSigmaHe3": "fNSigmaHe3 > 0.",
    "fTPCsignalPi": "fTPCsignalPi < 600.",
    "fNTPCclusHe": "fNTPCclusHe > 110",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 5.",
    "fDcaHe": "abs(fDcaHe) > 0.01"
  }

colliding_system: "PbPb"
is_matter: "both"
calibrate_he_momentum: True

